### ISSUE TITLE
Error Code 405 --> SSO

### ISSUE THREAD

**Issue by zunami** [Befox/cdav#45]
i have dolibarr installed on [Yunohost](https://github.com/YunoHost-Apps/dolibarr_ynh).
as per the readme I put cdav in the path dolibarr/htdocs/custom/
activated cdav and see it in dolibarr
BUT i tried with DAVx5 and can't connect.
I have tried these paths

https://mydomain.net/dolibarr/custom/cdav
https://mydomain.net/dolibarr/custom/cdav/server.php
https://mydomain.net/dolibarr/custom/cdav/server.php/principals/user/
https://mydomain.net/dolibarr/custom/cdav/server.php/addressbooks/user/default/

now i have seen that it is because of the login option SSO which i have no influence on at Dolibarr.

wish would be that also works.

DAVx5 Fehlercode
```
2022-04-07 07:41:51 141981 [HttpClient] <-- END HTTP (138-byte body)
2022-04-07 07:41:51 141981 [at.bitfire.dav4jvm.DavResource] Redirected, new location = https://mydomain.net/yunohost/sso/CODE
2022-04-07 07:41:51 141981 [HttpClient] --> PROPFIND https://mydomain.net/yunohost/sso/CODE h2
2022-04-07 07:41:51 141981 [HttpClient] Depth: 0
2022-04-07 07:41:51 141981 [HttpClient] User-Agent: DAVx5/4.2.0.3-gplay (2022/03/23; dav4jvm; okhttp/4.9.3) Android/12
2022-04-07 07:41:51 141981 [HttpClient] Accept-Language: de-AT, de;q=0.7, *;q=0.5
2022-04-07 07:41:51 141981 [HttpClient] Content-Type: application/xml; charset=utf-8
2022-04-07 07:41:51 141981 [HttpClient] Content-Length: 198
2022-04-07 07:41:51 141981 [HttpClient] Host: mydomain.net
2022-04-07 07:41:51 141981 [HttpClient] Connection: Keep-Alive
2022-04-07 07:41:51 141981 [HttpClient] Accept-Encoding: gzip
2022-04-07 07:41:51 141981 [HttpClient] 
2022-04-07 07:41:51 141981 [HttpClient] <?xml version='1.0' encoding='UTF-8' ?><propfind xmlns="DAV:" xmlns:CAL="urn:ietf:params:xml:ns:caldav" xmlns:CARD="urn:ietf:params:xml:ns:carddav"><prop><current-user-principal /></prop></propfind>
2022-04-07 07:41:51 141981 [HttpClient] --> END PROPFIND (198-byte body)
2022-04-07 07:41:51 141981 [HttpClient] <-- 405 https://mydomain.net/yunohost/sso/CODE (61ms)
2022-04-07 07:41:51 141981 [HttpClient] server: nginx
2022-04-07 07:41:51 141981 [HttpClient] date: Thu, 07 Apr 2022 05:41:43 GMT
2022-04-07 07:41:51 141981 [HttpClient] content-type: text/html
2022-04-07 07:41:51 141981 [HttpClient] content-length: 150
2022-04-07 07:41:51 141981 [HttpClient] x-sso-wat: You've just been SSOed
2022-04-07 07:41:51 141981 [HttpClient] content-security-policy: upgrade-insecure-requests
2022-04-07 07:41:51 141981 [HttpClient] content-security-policy-report-only: default-src https: data: blob: ; object-src https: data: 'unsafe-inline'; style-src https: data: 'unsafe-inline' ; script-src https: data: 'unsafe-inline' 'unsafe-eval'
2022-04-07 07:41:51 141981 [HttpClient] x-content-type-options: nosniff
2022-04-07 07:41:51 141981 [HttpClient] x-xss-protection: 1; mode=block
2022-04-07 07:41:51 141981 [HttpClient] x-download-options: noopen
2022-04-07 07:41:51 141981 [HttpClient] x-permitted-cross-domain-policies: none
2022-04-07 07:41:51 141981 [HttpClient] x-frame-options: SAMEORIGIN
2022-04-07 07:41:51 141981 [HttpClient] permissions-policy: interest-cohort=()
2022-04-07 07:41:51 141981 [HttpClient] strict-transport-security: max-age=63072000; includeSubDomains; preload
2022-04-07 07:41:51 141981 [HttpClient] 
2022-04-07 07:41:51 141981 [HttpClient] <html>
<head><title>405 Not Allowed</title></head>
<body>
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>

2022-04-07 07:41:51 141981 [HttpClient] <-- END HTTP (150-byte body)
2022-04-07 07:41:51 141981 [ui.setup.DavResourceFinder] No resource found
EXCEPTION at.bitfire.dav4jvm.exception.HttpException: HTTP 405 
at at.bitfire.dav4jvm.DavResource.checkStatus(DavResource.kt:5)
at at.bitfire.dav4jvm.DavResource.checkStatus(DavResource.kt:3)
at at.bitfire.dav4jvm.DavResource.processMultiStatus(DavResource.kt:2)
at at.bitfire.dav4jvm.DavResource.propfind(DavResource.kt:11)
at at.bitfire.davdroid.ui.setup.DavResourceFinder.getCurrentUserPrincipal(DavResourceFinder.kt:2)
at at.bitfire.davdroid.ui.setup.DavResourceFinder.discoverPrincipalUrl(DavResourceFinder.kt:28)
at at.bitfire.davdroid.ui.setup.DavResourceFinder.findInitialConfiguration(DavResourceFinder.kt:31)
at at.bitfire.davdroid.ui.setup.DavResourceFinder.findInitialConfiguration(DavResourceFinder.kt:4)
at at.bitfire.davdroid.ui.setup.DetectConfigurationFragment$DetectConfigurationModel$detectConfiguration$2.invoke(DetectConfigurationFragment.kt:6)
at at.bitfire.davdroid.ui.setup.DetectConfigurationFragment$DetectConfigurationModel$detectConfiguration$2.invoke(DetectConfigurationFragment.kt:1)
at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:1)
```

strangely enough i see the contacts in the weblink
![Screenshot 2022-05-02 154432](https://user-images.githubusercontent.com/4697822/166244135-bc877d88-66c6-4721-b6ae-35113a240c81.png)

**Comment by zunami** [comment]
I have also reported the problem to davx5 and they say that during the search the forwarding does not work

https://github.com/bitfireAT/davx5-ose/discussions/36#discussioncomment-2674689
